# .tangled/workflows/build.yml

when:
  - event: ["push"]
    branch: ["master"]

engine: "nixery"

# using the default values
clone:
  skip: false
  depth: 1
  submodules: false

dependencies:
  # nixpkgs
  nixpkgs:
    - nodejs
    - mdbook

steps:
  - name: "Build book"
    command: |
      mdbook build

  - name: "Check env"
    command: |
      echo "AUTH_TOKEN: $NETLIFY_AUTH_TOKEN"
      echo "SITE_ID: $NETLIFY_SITE_ID"
    environment:
      NETLIFY_AUTH_TOKEN: ${secrets.NETLIFY_TOKEN}
      NETLIFY_SITE_ID: ${secrets.NETLIFY_SITE_ID}

  - name: "Deploy to Netlify"
    command: |
      echo "builder:x:$(id -u):$(id -g):builder:/tmp:/bin/sh" >> /etc/passwd
      npx --yes netlify-cli deploy --dir=book --prod
    environment:
      NETLIFY_AUTH_TOKEN: ${secrets.NETLIFY_TOKEN}
      NETLIFY_SITE_ID: ${secrets.NETLIFY_SITE_ID}
      HOME: /tmp
      USER: builder
