# .tangled/workflows/build.yml

when:
  - event: ["push"]
    branch: ["master"]

engine: "nixery"

# using the default values
clone:
  skip: false
  depth: 1
  submodules: false

dependencies:
  # nixpkgs
  nixpkgs:
    - nodejs
    - mdbook

steps:
  - name: "Build book"
    command: |
      mdbook build

  - name: "Deploy to Netlify"
    command: |
      echo "builder:x:$(id -u):$(id -g):builder:/tmp:/bin/sh" >> /etc/passwd
      export NETLIFY_AUTH_TOKEN=$NETLIFY_TOKEN
      npx --yes netlify-cli deploy --dir=book --prod
    environment:
      HOME: /tmp
      USER: builder
